name: Deploy LabelService SDK to Workstations
on:
  push:
    branches:
      - main

env:
  REMOTE_IP: 67.210.192.18
  REMOTE_DIR: /home/aerotract/software/LabelService
  RESTART_SCRIPT: /home/aerotract/software/internal-tools/restart-service.sh

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - { name: "Sandra", port: 1953, method: "ssh" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WS006_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.WS006_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -p ${{ matrix.targets.port }} -H ${{ env.REMOTE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy updates via SSH to ${{ matrix.targets.name }}
        if: matrix.targets.method == 'ssh'
        run: |
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@${{ env.REMOTE_IP }} "cd ${{ env.REMOTE_DIR }}; git pull origin main"

      - name: Install updates on ${{ matrix.targets.name }}
        run: |
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@${{ env.REMOTE_IP }} "python3 -m pip install --user -r ${{ env.REMOTE_DIR }}/requirements.txt"
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@${{ env.REMOTE_IP }} "cd ${{ env.REMOTE_DIR }}; ${{ env.RESTART_SCRIPT }} LabelManagerService.service"
